# Generated by Django 4.2.28 on 2026-02-26 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='dependencies_installed',
            field=models.BooleanField(default=False, help_text='True when requirements.txt was installed successfully in the venv.'),
        ),
        migrations.AddField(
            model_name='execution',
            name='dependencies_log',
            field=models.TextField(blank=True, help_text='Raw log output from the dependency installation step (uv / pip).'),
        ),
        migrations.AddField(
            model_name='execution',
            name='python_version_used',
            field=models.CharField(blank=True, help_text="Python version that actually ran this execution (e.g. '3.11.8').", max_length=20),
        ),
        migrations.AddField(
            model_name='execution',
            name='runtime_config',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the runtime configuration passed to the ETL process (paths to inputs, outputs directory, etc.).'),
        ),
        migrations.AddField(
            model_name='execution',
            name='venv_path',
            field=models.CharField(blank=True, help_text='Filesystem path to the uv/virtual environment used for this run.', max_length=500),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.etl')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.execution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
